DEBUG = False
DATABASE_HOST = "localhost"
DATABASE_PORT = "5432"
DATABASE_DBNAME = "knoerden.dk"
DATABASE_USER = "postgres"
DATABASE_PASSWORD = ""

BCRYPT_ROUNDS = 16
PASSWORD_MIN_LENGTH = 6
INVITATION_KEY_LENGTH = 128

SECRET_KEY_LENGTH = 64
SECRET_KEY_FILE = "secret_key"
# SECRET_KEY set from SECRET_KEY_FILE
